#!/bin/bash
source logging-utils-stable.sh

log "redirect 'log' to log_info"
log0 "this is a severity" "this is a message"
log_info "log this as info"
log_warn "log this as warn"
log_error "log this as error"
log_debug "log this as debug"
